language: generic

sudo : required

services:
  - docker

before_install:
  - docker build -t ultramaks/docker-react -f Dockerfile.dev .

script:
  - docker run ultramaks/docker-react npm run test -- --coverage